POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZscG9ydGlsbGExIiwiaWQiOiI2MmNkNzA0YWY4NDJhNTBjYzg1ODA0ZmQiLCJpYXQiOjE2NTc2MzA4MTV9.ABJNQgtZU18YC07RvHedhMX3kavhHvBTOcUO_-TGDzE

{
  "title": "Blog name",
  "author": "Author name",
  "url": "localhost",
  "likes": 0011223344,
  "userId": "userId"
}