GET http://localhost:3003/api/blogs HTTP/1.1

###
GET http://localhost:3003/api/blogs/62c5a5e08415d0503c3087bd HTTP/1.1

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "test2",
  "author": "test",
  "url": "test",
  "likes": 0
}