POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "My second blog",
  "author": "flportilla",
  "url": "localhost, somewhere",
  "likes": 20210918,
  "userId": "62c8c34cb9a43e9fd0cea6ec"
}
###
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "flportilla2",
  "name": "Fabian Portilla",
  "password": "mysupersecretpassword"
}

###
GET http://localhost:3003/api/users HTTP/1.1




###
GET http://localhost:3003/api/blogs HTTP/1.1

###
GET http://localhost:3003/api/blogs/62c864f7757b6196ac6ff488 HTTP/1.1

###
DELETE http://localhost:3003/api/blogs/62c86634f2e2334fc91a3f54 HTTP/1.1

###
DELETE http://localhost:3003/api/blogs/ HTTP/1.1
###
PUT  http://localhost:3003/api/blogs/62c864f7757b6196ac6ff488 HTTP/1.1
Content-Type: application/json

{
  "title": "My f",
  "author": "flportilla",
  "url": "localhost, somewhere",
  "likes": 123
}
