GET http://localhost:3003/api/blogs HTTP/1.1

###
GET http://localhost:3003/api/blogs/62c6fe31b47a7b07b18353aa HTTP/1.1

###
DELETE http://localhost:3003/api/blogs/62c6fe0fb47a7b07b18353a4 HTTP/1.1

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "My first blog4",
  "author": "flportilla",
  "url": "localhost, somewhere",
  "likes": 20210918
}

